### ISSUE TITLE
Publish bundled package

### ISSUE THREAD

**Issue by maxwfreu** [maxwfreu/create-npm-react-package#1]
## Description
Should deploy a minified version of this package to npm to reduce file size.

## Tasks
- [ ] Install webpack as dev dependency
- [ ] Add webpack config to bundle into `/dist`
- [ ] Update `.npmignore`
- [ ] Update config to only publish contents of `/dist`
