### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by maxwfreu** [maxwfreu/create-npm-react-package#2]
## Description
Use `mocha` for unit testing and `chai` for assertions.

## Tasks
- [x] Move code into `src` folder
- [x] Create `tests` folder
- [x] Add tests for `PackageManager` class
